---
version: 2

output: prefixed

tasks:
  default:
    deps:
      - task: ci

  ci:
    cmds:
      - task: dependencies
      - task: lint
    desc: Run all CI-related tasks

  clean:
    cmds:
      - rm -fr node_modules
    desc: Delete all JavaScript dependencies

  dependencies:
    cmds:
      - task: dependencies:javascript
      - task: dependencies:php
    desc: Run all dependency-installing-related tasks

  dependencies:javascript:
    cmds:
      - npm install
    env:
      CI: true
    desc: Install JavaScript dependencies

  dependencies:php:
    cmds:
      - 'composer install --no-ansi --no-interaction --no-progress --no-suggest'
    desc: 'Install PHP dependencies'

  lint:
    cmds:
      - task: lint:javascript
      - task: lint:php
      - task: lint:sass
    desc: Run all linting-related tasks

  lint:javascript:
    cmds:
      - npx eslint --ignore-pattern '!.stylelintrc.js' .stylelintrc.js buildstatic/** javascript/**
    desc: Lint JavaScript files with ESLint

  lint:php:
    cmds:
      - 'vendor/bin/php-cs-fixer fix --allow-risky=yes --dry-run --diff --diff-format=udiff'
    desc: 'Lint PHP scripts with PHP Coding Standards Fixer'

  lint:sass:
    cmds:
      - 'npx stylelint _index.scss "sass/*.scss"'
    desc: Lint Sass files with Stylelint
